### ISSUE TITLE
More classic / legendary games parsed in tests

### ISSUE THREAD

**Issue by shnewto** [shnewto/pgn#12]
I think it'd be cool to add a few more PGNs of great games to our tests. It'd also be a good to know that more irl PGNs can be parsed :) 

For a good reference of how to go about adding a new PGN, checkout the `tests` directory. I imagine that PGNs themselves would be added to `tests/Shared.elm`, and tests added to `tests/ClassicPgnsTests.elm`.

If you're interested but still have questions, let me know!

Also, if you find a PGN that fails to parse, I'd love it if you still made a PR adding it to the test suite so we can give addressing any issues it uncovers in this library a go.

**Comment by carlosfrodrigues** [comment]
Hi, I'm interested in this one. Could you assign this for me? :)

**Comment by shnewto** [comment]
@carlosfrodrigues that would be fantastic! i've assigned this ticket to ya, let me know if i can help in any way!

**Comment by shnewto** [comment]
Closing now but would always welcome more of these classic games, thanks again @carlosfrodrigues!
